debug: true

spring:
  profiles:
#    active: server
    include: common

shiro:
  session:
    expiredTime: 1200

server:
  port: 7090

mapper:
  mappers: com.tosim.fileshare.common.config.data.MyMapper
  not-empty: false
  identity: MYSQL

mybatis:
  type-aliases-package: com.tosim.fileshare.common.domain
  configuration:
    mapUnderscoreToCamelCase: true

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count\=countSql
  page-size-zero: true
