debug: true

spring:
  #mysql配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fileshare?useSSL=false&encoding=utf8
    username: root
    password: "123456"
    #外网数据库ip
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    ###############以上为配置druid添加的配置########################################

  #redis配置
  redis:
    database: 0
    host: 127.0.0.1
    password:
#    host: 47.96.239.50
#    password: THlc123456
    port: 6379
    timeout: 0
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
#  profiles:
#    active: dev

druid:
  username: root
  password: "056210"

pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count\=countSql

mybatis:
  type-aliases-package: com.tosim.fileshare.common.domain
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  level:
    com:
      tosim:
        fileshare:
          common:
            mapper: debug
          web: trace
          manager: trace
